### ISSUE TITLE
Datengrundlage

### ISSUE THREAD

**Issue by Boerd** [tuwien-geoweb/g03-2014#10]
Punktdiagramme:  ÖV- Netz, Nahversorgern, Schulen, Ärzten,
Flächendiagramme: Bevölkerungsdichte, Haushaltseinkommen, Bildungsstand 
OPEN DATA

**Comment by ahocevar** [comment]
Diagramme? Thematische Karten, oder?

**Comment by ahocevar** [comment]
Bzw. Kartenthemen.

**Comment by Boerd** [comment]
Thematische Karten.
