### ISSUE TITLE
Layer auf Geoserver erstellen

### ISSUE THREAD

**Issue by Boerd** [tuwien-geoweb/g03-2014#14]

**Comment by Boerd** [comment]
@ahocevar 
Beim Verwenden des Select Befehls am Geoserver bekommen wir eine Fehlermeldung, welche wir nicht verstehen, da sie lautet "no such column: pst045212". pst045212 ist jedoch der Standardwert und nicht die column.
![fehlermeldung](https://cloud.githubusercontent.com/assets/9716561/5614013/6d38df40-94ec-11e4-8110-3f39aa3b496b.jpg)

**Comment by Boerd** [comment]
@ahocevar 
Natürlich konnte die obige Abfrage nicht funktionieren. Haben das Problem bereits gelöst - also die Frage einfach ignorieren ;)

**Comment by Boerd** [comment]
@ahocevar @jbroetha 
Der Geoserver dürfte down sein :)

**Comment by jbroetha** [comment]
Geoserver sollte wieder laufen …

MfG
J. Bröthaler

Von: Boerd [mailto:notifications@github.com]
Gesendet: Dienstag, 06. Jänner 2015 12:44
An: tuwien-geoweb/g03-2014
Cc: Bröthaler Johann
Betreff: Re: [g03-2014] Layer auf Geoserver erstellen (#14)

@ahocevarhttps://github.com/ahocevar @jbroethahttps://github.com/jbroetha
Der Geoserver dürfte down sein :)
