### ISSUE TITLE
Anwendung und Design

### ISSUE THREAD

**Issue by danpro** [tuwien-geoweb/g03-2014#16]
Der Nutzer soll auf einer eingebetteten Karte von Wien nach den definierten Kriterien eine Wohnstandort-Wahl treffen können. Die einzelnen Datenebenen können differenziert aber auch kombiniert mittels Dropdowntabelle angewählt werden.

**Comment by ahocevar** [comment]
> Die einzelnen Datenebenen können differenziert aber auch kombiniert mittels Dropdowntabelle angewählt werden.

Dropdown und kombiniert schließen sich nach gängigen UI-Design Richtlinien aus. Bitte also noch einmal durchdenken bzw. eine Skizze machen, wie das aussehen soll.

**Comment by Boerd** [comment]
Jene Daten, welche sich auf die Bezriksfläche beziehen, werden mittels Dropdown auswählbar sein. Zusätzlich wird mittels Checkbox die zugrundeliegende Shapedatei änderbar sein.
