### ISSUE TITLE
Projektplanerstellung

### ISSUE THREAD

**Issue by Boerd** [tuwien-geoweb/g03-2014#18]
@ahocevar 

Unsere Projektplanung ist unter https://github.com/tuwien-geoweb/g03-2014/issues?q=is%3Aissue+is%3Aopen+label%3Aproject bzw. auf unserer Gruppenhomepage http://student.ifip.tuwien.ac.at/geoweb/2014/g03/ zu finden.

**Comment by ahocevar** [comment]
Ich habe zu ein paar Tickets Kommentare hinzugefügt. Im Prinzip könnt ihr loslegen, macht euch aber im eigenen Interesse zum UI (speziell das Layer-Dropdown) noch Gedanken.
