### ISSUE TITLE
HÜ2

### ISSUE THREAD

**Issue by harbar** [tuwien-geoweb/g03-2014#6]
Aufgabe erledigt @ahocevar

**Comment by ahocevar** [comment]
Bitte das Ergebnis auf der Homepage verlinken und/oder hier den Link posten - sonst weiß ich ja nicht, wo ich nach eurer Abgabe suchen muss.

**Comment by harbar** [comment]
@ahocevar link auf HP eingebaut http://student.ifip.tuwien.ac.at/geoweb/2014/g03/homepage/home.html -> Feedback; sowie direkt unter http://tuwien-geoweb.github.io/g03-2014/Block4/feedback_map.html
