### ISSUE TITLE
Difficulties Exercise Block 5

### ISSUE THREAD

**Issue by Boerd** [tuwien-geoweb/g03-2014#7]
@ahocevar 
Das Zentrieren auf den Standort funktioniert; 
Das Setzen eines Punktes auf den Suchort ebenfalls. 
Nicht klar ist ob wir den Accuracy Circle der Geolocation richtig eingebaut haben bzw. ob der Befehl überhaupt stimmt. Wir haben versucht den getView-Befehl der Boundingbox mit einem getView-Befehl einer Geometry über ein logisches "und" ("&&") zu verbinden. Der Browser gibt zwar keine Fehlermeldung aus, aber die Ansicht unterscheidet sich nicht von jener der Boundingboxabfrage. 
html-Datei: https://github.com/tuwien-geoweb/g03-2014/blob/gh-pages/block5/map_test2.html
Browser-Link: http://tuwien-geoweb.github.io/g03-2014/block5/map_test2.html

**Comment by Boerd** [comment]
@ahocevar 
Wir haben den Befehl nun in die SetNewLocation() geschrieben. Wenn man die Seite aufruft kommt jedoch die Fehlermeldung "Das Objekt unterstützt die Eigenschaft oder Methode "maxZoom" nicht". Obwohl in der Openlayers Documentation unter fit.Geometry(geometry, size, opt_options) steht und in opt_options "maxZoom" als Möglichkeit angeführt wird. Sind wir hier am richtigen Weg?
https://github.com/tuwien-geoweb/g03-2014/blob/gh-pages/block5/map_test2.html
http://tuwien-geoweb.github.io/g03-2014/block5/map_test2.html

**Comment by ahocevar** [comment]
opt_options ist ein Object Literal. Also mit key-value Paaren in geschwungener Klammer. Detaillierte Antwort siehe Committee-Kommentar.

**Comment by Boerd** [comment]
@ahocevar 
Danke für die Hilfe soweit! Das mit dem Button sollte nun auch gelöst sein. Den Punktstyle haben wir ebenfalls geändert. Beim Versuch die Karte auf den eigenen Standort zu zentrieren kommt jetzt jedoch die Fehlermeldung "SCRIPT5007: Die Eigenschaft "j" eines undefinierten oder Nullverweises kann nicht abgerufen werden." -  "Datei: ol.js, Zeile: 62, Spalte: 267". 
https://github.com/tuwien-geoweb/g03-2014/blob/gh-pages/block5/map_test2.html
http://tuwien-geoweb.github.io/g03-2014/block5/map_test2.html

**Comment by ahocevar** [comment]
Das kommt daher, dass zum Zeitpunkt, wo der `change:position` Event gefeuert wird, die accuracyGeometry noch nicht berechnet ist. Das könnt ihr aber leicht beheben, indem ihr einen anderen Event verwendet:

```
geolocation.on('change'
```

statt

```
geolocation.on(`change:position`
```
